# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Authtest' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
    sleep(5)
  end
  it 'regtest' do
    @driver.get('http://localhost:3000/calc/input')
    expect(@driver.find_element(:xpath, '//p[3]').text).to eq("Sign up first.")
  end
end
