# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Regtest' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
    sleep(5)
  end
  it 'regtest' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:link_text, 'New user').click
    @driver.find_element(:id, 'user_username').click
    @driver.find_element(:id, 'user_username').send_keys('test')
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys('test@example.com')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('12345678')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:id, 'email').click
    @driver.find_element(:id, 'email').send_keys('test@example.com')
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('12345678')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:id, 'array').click
    @driver.find_element(:id, 'array').send_keys('1 2 3 6 28 5 496')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, 'tr:nth-child(2) > td:nth-child(2)').text).to eq('["6", "28"]')
    @driver.find_element(:link_text, 'To userlist').click
    @driver.find_element(:link_text, 'Back to sign in').click
    @driver.find_element(:link_text, 'Log out').click
  end
end
